version: '3.3'
services:
  server:
    restart: always
    container_name: "template-server"
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    environment:
      - MODE=PROD # PROD or not specified
    privileged: true