version: '3.3'
services:
  sensor-monitor-server:
    restart: always
    container_name: "sensor-monitor-server"
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5001:5000"
    # environment:
      # - MODE=PROD # PROD or not specified, not specified will be in dev mode
    privileged: true

  sensor-db:
    restart: always
    image: postgres:latest
    container_name: sensor-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: sram-admin 
      POSTGRES_PASSWORD: sramsram-admin
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  sensor-frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: dockerfile
    environment:
      - PUBLIC_BASE_URL=http://192.168.0.70:5001
      - PUBLIC_SOCKET_URL=http://192.168.0.70:5001
    ports:
      - "3000:3000"